# Generated by Django 5.2.7 on 2025-10-24 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulos_aprendizaje', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('opciones', models.JSONField()),
                ('respuesta_correcta', models.CharField(max_length=1)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos_aprendizaje.modulo')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('necesita_refuerzo', models.BooleanField(default=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos_aprendizaje.modulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
